### ISSUE TITLE
netcdf build fails checks

### ISSUE THREAD

**Issue by jn4snz** [pwolfram/homebrew-mpas#1]
The netcdf build fails checks. If I recall correctly, netcdf needs a specific version of fortran. 

Moreover, again, if I remember correctly, specific versions of packages work better than others when compiling/running MPAS. For example on my old machine I deliberately ended up using these versions of packages:

gcc 4.8
netcdf 4.3.3.1_4
parallel-netcdf 1.4.1
pio 1.7.2

But I forget how to force these packages using brew. I'll look into fixing this, but if you know how to do this, please let me know.

Juan

**Comment by jn4snz** [comment]
forgot to mention that the formula for netcdf installs and uses the latest version of gcc, 6.3.* (?)

**Comment by jn4snz** [comment]
The formulas in this repo install netcdf, parallel-netcdf and pio versions I listed above. The issue then is getting the installation to use a version of fortran that does not fail.

**Comment by pwolfram** [comment]
My install uses `gfortran 6.2.0`.  @jn4snz, can you please dump the error from the failed `make check` for netcdf?

**Comment by pwolfram** [comment]
My versions installed for the record:

hdf5 1.8.12 1.8.17
gcc 5.1.0 6.2.0
gfortran 4.8.2
pio 1.7.2
netcdf 4.3.3.1
parallel-netcdf 1.4.1

**Comment by jn4snz** [comment]
Those versions work. But the formula pulls later versions of gcc and hdf5. There are known issues with the latter:
http://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg13573.html

I think you'll have to use gcc@4.8

Also, using hdf5@1.8 will be tricky, see below:

juansaenz@pn1714459: ~ $ 
$ brew install hdf5@1.8
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
jfrog-cli-go

==> Installing hdf5@1.8 from homebrew/science
==> Downloading https://homebrew.bintray.com/bottles-science/hdf5@1.8-1.8.18.el_capitan.bottle.tar.g
######################################################################## 100.0%
==> Pouring hdf5@1.8-1.8.18.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

This is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/hdf5@1.8/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/hdf5@1.8/lib
    CPPFLAGS: -I/usr/local/opt/hdf5@1.8/include

==> Summary
🍺  /usr/local/Cellar/hdf5@1.8/1.8.18: 181 files, 10.6M

**Comment by jn4snz** [comment]
The check that fails is:

/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
PASS: tst_dims
PASS: tst_dims2
PASS: tst_dims3
FAIL: tst_files
PASS: tst_files4
PASS: tst_vars
PASS: tst_varms

**Comment by pwolfram** [comment]
@jn4snz, did you ultimately get this to work?  I'm trying to figure out if we should close this issue.

**Comment by pwolfram** [comment]
Turns out this requires open-mpi@1.6.  See #3

**Comment by pwolfram** [comment]
@jn4snz, I believe #3 covers this issue.  Please reopen if you disagree.
