### ISSUE TITLE
Unable to install PIO using homebrew-mpas on CentOS Linux 7

### ISSUE THREAD

**Issue by soto97** [pwolfram/homebrew-mpas#5]
I am trying to use the homebrew-mpas recipe to set up MPAS on a CentOS Linux release 7.4.1708 machine. I am able to install everything but PIO. When I isolate the PIO command in the install.sh script, and just run that PIO command, here is the error message I get:
``` bash
[eurus] homebrew-mpas $ brew install pwolfram/mpas/pio --build-from-source
==> Installing pio from pwolfram/mpas
==> Downloading https://github.com/NCAR/ParallelIO/archive/pio1_7_2.tar.gz
Already downloaded: /home/asoto/.cache/Homebrew/downloads/84ac1c132c404094b3838e9fb9007608d5877cc19b5f62d5d694fe59895677b0--ParallelIO-pio1_7_2.tar.gz


==> ./configure --prefix=/home/asoto/.linuxbrew/Cellar/pio/1.7.2
Last 15 lines from /home/asoto/.cache/Homebrew/Logs/pio/01.configure:
Machine=x86_64
OS=Linux
checking Fortran 90 module extension... mod
checking Fortran 90 module inclusion flag... -I
using NETCDF_PATH from environment
checking for Fortran flag to compile .F90 files... (cached) none
checking for hdf5... yes
checking for H5open in -lhdf5... yes
checking for H5Dclose in -lhdf5_hl... yes
configure: Fortran not checked for yet
checking for netcdf... /usr/local/
checking for library containing nc_inq_libvers... -lnetcdf
checking for library containing NF_INQ_LIBVERS... -lnetcdff
checking for f90 netCDF interface... no
configure: error: netcdf.mod not found in NETCDF_PATH/include                             check the environment variable NETCDF_PATH

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/pwolfram/homebrew-mpas/issues
```

The install claims that the netcdf.mod file is missing. However, if I got to `$NETCDF_PATH/include` then I see that I have the netcdf.mod file. 
``` bash
[eurus] homebrew-mpas $ ls $NETCDF_PATH/include
ncAtt.h           ncEnumType.h   ncInt.h         ncUint.h      netcdf4_f03.mod                 netcdf.h            netcdf_nc_interfaces.mod
ncByte.h          ncException.h  ncOpaqueType.h  ncUshort.h    netcdf4_nc_interfaces.mod       netcdf.hh           netcdf_nf_data.mod
ncChar.h          ncFile.h       ncShort.h       ncvalues.h    netcdf4_nf_interfaces.mod       netcdf.inc          netcdf_nf_interfaces.mod
ncCheck.h         ncFloat.h      ncString.h      ncVarAtt.h    netcdf_aux.h                    netcdf_mem.h        test_utilities.h
ncCompoundType.h  ncGroupAtt.h   ncType.h        ncVar.h       netcdfcpp.h                     netcdf_meta.h       typesizes.mod
ncDim.h           ncGroup.h      ncUbyte.h       ncVlenType.h  netcdf_f03.mod                  netcdf.mod
ncDouble.h        ncInt64.h      ncUint64.h      netcdf        netcdf_fortv2_c_interfaces.mod  netcdf_nc_data.mod
[eurus] homebrew-mpas $
```

It's not clear why the code is not working. Is this an issue with the brew recipe? Or with the PIO installation software?

Thanks!

**Comment by pwolfram** [comment]
@soto97, the issue is that NETCDF isn't being found: `configure: error: netcdf.mod not found in NETCDF_PATH/include  `

Did you install PIO using the whole stack as discussed at the readme: https://github.com/pwolfram/homebrew-mpas?

I'm guessing you need to check that https://github.com/pwolfram/homebrew-mpas/blob/master/pio.rb#L15 is correct...

**Comment by soto97** [comment]
Okay. I figured it out. What I didn't understand was that setting the environmental variable, `NETCDF_PATH` was not enough. I had to download a copy of `pio.rb` and run it locally with the command `brew install pio.rb` (entered in the directory where I had pio.rb). I wasn't aware until now that you could run a homebrew formula locally in this way. Once I did this, I got everything compiled, including MPAS.

Thanks for the pointer above. And thanks for sharing this homebrew formula. With your formula I now have MPAS compiled and running on a Linux machine and two Apple machines (including a MacBook Air laptop).

**Comment by pwolfram** [comment]
Awesome @soto97, glad to hear the great news!
